title: JTD Exercise
description: Vistula Tech Writing school 2024
theme: just-the-docs
color_scheme: dark 

url: https://docwizard.github.io/jtd-exercise

aux_links:
  Template Repository: https://github.com/DocWizard/jtd-exercise